[package]
name = "auto"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
notify = "5.1.0"

[profile.release]
strip = true
opt-level = 's'
lto = true
codegen-units = 1
